// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: invoice.sql

package db

import (
	"context"
	"time"
)

const addNoItemsInvoice = `-- name: AddNoItemsInvoice :one
INSERT INTO invoices (
    customer_id, 
    vendor_id, 
    issue_date, 
    due_date, 
    discount_rate
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING invoice_number, customer_id, vendor_id, issue_date, due_date, status, subtotal, discount_rate, discount, total_amount, billing_currency, note
`

type AddNoItemsInvoiceParams struct {
	CustomerID   int64     `json:"customer_id"`
	VendorID     int64     `json:"vendor_id"`
	IssueDate    time.Time `json:"issue_date"`
	DueDate      time.Time `json:"due_date"`
	DiscountRate int64     `json:"discount_rate"`
}

func (q *Queries) AddNoItemsInvoice(ctx context.Context, arg AddNoItemsInvoiceParams) (Invoice, error) {
	row := q.db.QueryRow(ctx, addNoItemsInvoice,
		arg.CustomerID,
		arg.VendorID,
		arg.IssueDate,
		arg.DueDate,
		arg.DiscountRate,
	)
	var i Invoice
	err := row.Scan(
		&i.InvoiceNumber,
		&i.CustomerID,
		&i.VendorID,
		&i.IssueDate,
		&i.DueDate,
		&i.Status,
		&i.Subtotal,
		&i.DiscountRate,
		&i.Discount,
		&i.TotalAmount,
		&i.BillingCurrency,
		&i.Note,
	)
	return i, err
}
