// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: invoice.sql

package db

import (
	"context"
	"time"
)

const addLineItem = `-- name: AddLineItem :one
INSERT INTO line_items (
    invoice_number,
    description,
    quantity,
    unit_price,
    total_price
) VALUES ($1, $2, $3, $4, $5) RETURNING id, invoice_number, description, quantity, unit_price, total_price
`

type AddLineItemParams struct {
	InvoiceNumber int64  `json:"invoice_number"`
	Description   string `json:"description"`
	Quantity      int64  `json:"quantity"`
	UnitPrice     int64  `json:"unit_price"`
	TotalPrice    int64  `json:"total_price"`
}

func (q *Queries) AddLineItem(ctx context.Context, arg AddLineItemParams) (LineItem, error) {
	row := q.db.QueryRow(ctx, addLineItem,
		arg.InvoiceNumber,
		arg.Description,
		arg.Quantity,
		arg.UnitPrice,
		arg.TotalPrice,
	)
	var i LineItem
	err := row.Scan(
		&i.ID,
		&i.InvoiceNumber,
		&i.Description,
		&i.Quantity,
		&i.UnitPrice,
		&i.TotalPrice,
	)
	return i, err
}

const addNoItemsInvoice = `-- name: AddNoItemsInvoice :one
INSERT INTO invoices (
    customer_id, 
    vendor_id, 
    issue_date, 
    due_date, 
    discount_rate
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING invoice_number, customer_id, vendor_id, issue_date, due_date, status, subtotal, discount_rate, discount, total_amount, billing_currency, note
`

type AddNoItemsInvoiceParams struct {
	CustomerID   int64     `json:"customer_id"`
	VendorID     int64     `json:"vendor_id"`
	IssueDate    time.Time `json:"issue_date"`
	DueDate      time.Time `json:"due_date"`
	DiscountRate int64     `json:"discount_rate"`
}

func (q *Queries) AddNoItemsInvoice(ctx context.Context, arg AddNoItemsInvoiceParams) (Invoice, error) {
	row := q.db.QueryRow(ctx, addNoItemsInvoice,
		arg.CustomerID,
		arg.VendorID,
		arg.IssueDate,
		arg.DueDate,
		arg.DiscountRate,
	)
	var i Invoice
	err := row.Scan(
		&i.InvoiceNumber,
		&i.CustomerID,
		&i.VendorID,
		&i.IssueDate,
		&i.DueDate,
		&i.Status,
		&i.Subtotal,
		&i.DiscountRate,
		&i.Discount,
		&i.TotalAmount,
		&i.BillingCurrency,
		&i.Note,
	)
	return i, err
}
