// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"time"
)

type Customer struct {
	ID      int64  `json:"id"`
	Name    string `json:"name"`
	Phone   string `json:"phone"`
	Address string `json:"address"`
	Email   string `json:"email"`
}

type Invoice struct {
	InvoiceNumber   int64     `json:"invoice_number"`
	CustomerID      int64     `json:"customer_id"`
	VendorID        int64     `json:"vendor_id"`
	IssueDate       time.Time `json:"issue_date"`
	DueDate         time.Time `json:"due_date"`
	Status          string    `json:"status"`
	Subtotal        int64     `json:"subtotal"`
	DiscountRate    int64     `json:"discount_rate"`
	Discount        int64     `json:"discount"`
	TotalAmount     int64     `json:"total_amount"`
	BillingCurrency string    `json:"billing_currency"`
	Note            string    `json:"note"`
}

type LineItem struct {
	ID            int64  `json:"id"`
	InvoiceNumber int64  `json:"invoice_number"`
	Description   string `json:"description"`
	Quantity      int64  `json:"quantity"`
	UnitPrice     int64  `json:"unit_price"`
	TotalPrice    int64  `json:"total_price"`
}

type Vendor struct {
	ID              int64  `json:"id"`
	Name            string `json:"name"`
	Phone           string `json:"phone"`
	Address         string `json:"address"`
	Email           string `json:"email"`
	BankAccountName string `json:"bank_account_name"`
	BankAccountNo   int64  `json:"bank_account_no"`
	BankName        string `json:"bank_name"`
}
