// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"context"
)

type Querier interface {
	AddCustomer(ctx context.Context, arg AddCustomerParams) (Customer, error)
}

var _ Querier = (*Queries)(nil)
