// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"context"
)

type Querier interface {
	AddCustomer(ctx context.Context, arg AddCustomerParams) (Customer, error)
	AddLineItem(ctx context.Context, arg AddLineItemParams) (LineItem, error)
	AddNoItemsInvoice(ctx context.Context, arg AddNoItemsInvoiceParams) (Invoice, error)
	AddVendor(ctx context.Context, arg AddVendorParams) (Vendor, error)
	GetInvoiceLineItems(ctx context.Context, invoiceNumber int64) ([]LineItem, error)
	UpdateInvoice(ctx context.Context, arg UpdateInvoiceParams) (Invoice, error)
}

var _ Querier = (*Queries)(nil)
