// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: vendor.sql

package db

import (
	"context"
)

const addVendor = `-- name: AddVendor :one
INSERT INTO vendors (name, phone, address, email, bank_account_name, bank_account_no, bank_name)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, name, phone, address, email, bank_account_name, bank_account_no, bank_name
`

type AddVendorParams struct {
	Name            string `json:"name"`
	Phone           string `json:"phone"`
	Address         string `json:"address"`
	Email           string `json:"email"`
	BankAccountName string `json:"bank_account_name"`
	BankAccountNo   int64  `json:"bank_account_no"`
	BankName        string `json:"bank_name"`
}

func (q *Queries) AddVendor(ctx context.Context, arg AddVendorParams) (Vendor, error) {
	row := q.db.QueryRow(ctx, addVendor,
		arg.Name,
		arg.Phone,
		arg.Address,
		arg.Email,
		arg.BankAccountName,
		arg.BankAccountNo,
		arg.BankName,
	)
	var i Vendor
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Address,
		&i.Email,
		&i.BankAccountName,
		&i.BankAccountNo,
		&i.BankName,
	)
	return i, err
}
